"""
Django settings for trivia_backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os  # Import os to access environment variables

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'default-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['battletrivia-53f5e19174e5.herokuapp.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
    'social_django',
    'corsheaders',  # This is correctly placed here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS Middleware
    'django.contrib.sessions.middleware.SessionMiddleware',  # Make sure this line is present
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]


ROOT_URLCONF = 'trivia_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                # Removed 'corsheaders.middleware.CorsMiddleware' from here
            ],
        },
    },
]

WSGI_APPLICATION = 'trivia_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Existing STATIC_URL setting
STATIC_URL = '/static/'

# Add the STATIC_ROOT setting if not already present
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SOCIAL_AUTH_TWITCH_KEY = os.getenv('TWITCH_CLIENT_ID')
SOCIAL_AUTH_TWITCH_SECRET = os.getenv('TWITCH_SECRET')

print("Twitch Client ID:", SOCIAL_AUTH_TWITCH_KEY)
print("Twitch Secret:", SOCIAL_AUTH_TWITCH_SECRET)



# Set up the authentication backends
AUTHENTICATION_BACKENDS = (
    'social_core.backends.twitch.TwitchOAuth2',  # Twitch OAuth backend
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
)

# Define the redirect URLs after login/logout
LOGIN_REDIRECT_URL = '/'  # Redirect here after successful login
LOGOUT_REDIRECT_URL = '/'  # Redirect here after logout

# Additional social-auth settings
SOCIAL_AUTH_URL_NAMESPACE = 'social'

# Include the OAuth redirect URL
TWITCH_REDIRECT_URI = 'http://localhost:8000/auth/complete/twitch/'  # Update this for production

# Allow CORS if needed in development
CORS_ORIGIN_ALLOW_ALL = True