# Generated by Django 5.1.1 on 2024-09-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_twitchchannel_delete_activechannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchchannel',
            name='channel_name',
            field=models.CharField(max_length=255),
        ),
    ]
